dist: trusty
sudo: false

language: node_js

node_js: node # lastest

cache: yarn

before_install:
  # Install the latest yarn version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn --version

install:
  - yarn install

script:
  - yarn run test
  - yarn run lint
  - yarn run flow
  - yarn run smoke cjs 15.6.2
  - yarn run smoke esm 15.6.2
  - yarn run smoke cjs 16.1.0
  - yarn run smoke esm 16.1.0
  - yarn run smoke cjs latest
  - yarn run smoke esm latest
  - yarn run smoke cjs next
  - yarn run smoke esm next
